### PR TITLE
feat: adding CD pipeline for UAT and PROD deployment

### PR DESCRIPTION
**Pull request by captainboris**
- adding 2 CD pipelines
- adding 2 images for the readme
- updating the readme with new CD pipeline instructions
- updating the CI pipeline to include the new CD pipelines

-about PR triggered testing @Chris-Wang : 
The 2 CD pipelines are triggered manually by "workflow_dispatch", due to the nature of GitHub Actions, unfortunately, this cannot be triggered due to the nature of GitHub actions until the CD pipeline is merged in the default branch (Dev in our case), I forked the platform_api repo to my own Github account and tested in my forked duplication. The test results are as follow:
image
image
below are my aws repos that have pushes from the CD runs
uat repo:
image
prod repo:
image

### CODE REVIEW

**Comment by zavier250** [comment]
Does CD part trigger the CI workflow through workflow_call?

**Comment by captainboris** [comment]
> Does CD part trigger the CI workflow through workflow_call?

For uat yes, for prod I think there is no need for it

**Comment by zavier250** [comment]
Looks good from my aspect

**Review by Chris-Wang — APPROVED** [review]
LGTM

**Pull request merged**
