### PR TITLE
feat: implement delete exchange key backend

### PR DESCRIPTION
**Pull request by s3713434**
feat: implement delete exchange key backend

Implemented backend functionality for deleting an exchange key when both the user ID and exchange key ID match. If the deletion is unsuccessful (affected=0), an error is returned. Additionally, an error is returned if either the user ID or exchange key ID do not match. Jest testing has been added to ensure functionality.

Resolve CP-12

[CP-12](https://beequant.atlassian.net/browse/CP-12?atlOrigin=eyJpIjoiYmFjNzEyNjRjMDAxNDM0OWE2MmJiMjI5MTcyZjI0MjAiLCJwIjoiaiJ9)

---

## What happens here?
- Implemented the delete exchange key backend feature.
- Ensured the exchange key is deleted only when both user ID and exchange key ID match.
- Return an error if `affected=0`, meaning no records were deleted.
- Return an error if the user ID and exchange key ID do not match.
- Added Jest tests to ensure the delete functionality works as expected.

## How do I know this is working?
1. Make a delete request with valid user ID and exchange key ID.
2. Confirm that the exchange key is successfully deleted.
3. Test with invalid user ID or exchange key ID, and ensure the correct error message is returned.
4. Simulate cases where no records are affected (`affected=0`) and verify that the error is returned.
5. Run the Jest tests to ensure the backend delete functionality is working correctly.

##GraphQL Playground Screenshots
code-200
type error
wrong key

### CODE REVIEW

**Review by Chris-Wang — APPROVED** [review]
LGTM

**Review by Chris-Wang — CHANGES_REQUESTED** [review]
Please resolve conflict

**Comment by s3713434** [comment]
> Please resolve conflict

Conflict has been resolved

**Review by Chris-Wang — CHANGES_REQUESTED** [review]
Good work!

Just need to resolve conflicts and squash commits

**Review by Chris-Wang — APPROVED** [review]
LGTM

**Pull request merged**
